CREATE TABLE TIMELINE_ITEMS (
    ID SERIAL PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    SERVICE_ID VARCHAR(50) NOT NULL,
    CONTENTS TEXT NOT NULL,
    CREATED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)